# Site settings
title: fernando.blat.es
description: >-
  Blog y notas personales
lang: es-ES
timezone: Europe/Madrid
image: assets/img/avatar.png
repo: https://github.com/ferblape/blog.git
mode: light # default theme "dark" | "light"

# Profile settings
author:
  name: Fernando Blat
  bio: - blog y notas personales 
  username: ferblape
  email: fernando@blat.es
  avatar: /assets/img/avatar.png

# Url settings
url: "https://fernando.blat.es"
baseurl:
permalink: /:title/
google_analytics:
fb_appid:

# Collection setting
collections:
  posts:
    output: true
  tumblr_files:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - bin

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-postfiles
